azure servicefabric service remove fabric:/SimpleContainerApp/StatelessFrontendService
azure servicefabric service remove fabric:/SimpleContainerApp/StatelessBackendService
azure servicefabric application remove fabric:/SimpleContainerApp
azure servicefabric application type unregister SimpleContainerApp 1.0